# Generated by Django 4.2 on 2023-06-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10)),
                ('option1', models.CharField(max_length=10)),
                ('option2', models.CharField(max_length=10)),
            ],
        ),
    ]
