# Generated by Django 4.2.1 on 2024-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizapp', '0002_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quiz_type', models.CharField(choices=[('blue', 'blue'), ('blue_extra', 'blue_extra'), ('blue_yellow', 'blue_yellow'), ('blue_yellow_extra', 'blue_yellow_extra')], max_length=20)),
                ('data', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
