# Generated by Django 4.2.1 on 2024-05-18 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
