# Generated by Django 4.2.1 on 2024-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_quiz_created_at_quiz_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='next_page_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
