# Generated by Django 4.2.1 on 2024-09-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_quiz_next_page_link_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('blue', 'Blue'), ('blue_extra', 'Blue Extra'), ('blue_yellow', 'Blue Yellow'), ('blue_yellow_extra', 'Blue Yellow Extra')], max_length=20),
        ),
    ]
