# Generated by Django 4.2.1 on 2024-10-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_pageview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
