# Generated by Django 4.2.1 on 2024-10-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_pageview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
